### ISSUE TITLE
Special Research is lost after Collapse

### ISSUE THREAD

**Issue by reAsOn2010** [awWhy/Fundamental#11]
In stage "Interstellar", The research "Mass transfer" is back to 0 after Collapse. Is this correct? Seems all other special research is not losing after reset.

**Comment by awWhy** [comment]
Upgrades/Researches that don't have any real effect (like unlock new stuff), do not get reset, there are few expections. Nova research is one of them (losing it after each Collapse woudn't do much), also all Interstellar upgrades
