### ISSUE TITLE
About the Automation of Collapse..

### ISSUE THREAD

**Issue by Liwers-Loor** [awWhy/Fundamental#12]
Since it shows the timer of solar mass' hardcap in v0.1.9, we can be pretty sure when should be the best time of collapse..

However, the Auto Collapse upgrade is still usually collapse on a wrong point..

So how about add a 2nd level of Auto Collapse that makes it can auto activate when the timer reaches 0..

That will be more friendly for playing through..

Meow..!

**Comment by awWhy** [comment]
I don't remember what v0.1.9 auto Collapse looked like, but v0.2.1 should have everything user need to make it good enough
