### ISSUE TITLE
The game is not loading.

### ISSUE THREAD

**Issue by DevilishWill** [awWhy/Fundamental#4]
The game is not loading for me.

**Comment by DevilishWill** [comment]
Nvm it was related to my browser, but I remember being able to play this game while on this browser a few months ago

**Comment by awWhy** [comment]
I don't really think it's browser related (unless you are using internet exploler), you can check console and post error here

**Comment by DevilishWill** [comment]
Is this what you are talking about?

![image](https://user-images.githubusercontent.com/126983940/222969073-0f49e076-1601-46a0-b299-11f0bee49490.png)

**Comment by awWhy** [comment]
Looks like there was some issue with updating save file to correct version

**Comment by awWhy** [comment]
Okay bug fix is pushed, try to launch game again. This time should have no issues
(I assume that your save file version was v0.0.7 or v0.0.8, or v0.0.9; If it didn't got fixed then send me your save file)
