### ISSUE TITLE
Could you add a QoL function to tell us how long should we wait..?

### ISSUE THREAD

**Issue by Liwers-Loor** [awWhy/Fundamental#5]
Hi awWhy,

I'm thinking if you cound add a timer after each Generator that it may show accurate seconds when the buying multiplier is set and to tell us how long we should wait to reach the next buying target..

Bacause there are lots of content are 'influenced by unspent elements', the players may not spent until they stock large enough sum of elements and buy a stack of 10/20/50/100 generators.. 

More than this, it's also useful on Autobuyers and Achievement: the former one tells the players how fast is the current buying speed, and later one gives the player a fare-enough excuse to wait for a little longer..

Well, I don't know your roadmap, but I think this is just a QoL function which will not delay your current development, and I found it quite so helpful and enhance gaming experience greatly..

I really like your game, despite I didn't turn off my computer for about a week long from then..

Hope to hear from you soon..

Meow..!

**Comment by awWhy** [comment]
I personally think that 2x save that auto does, is already good enough
Elements^0.01 gets weaker after each increase in Elements, so much that getting 1 extra Star I'm pretty sure always better than holding back
And finally adding anything like this, would require full duplication of production calculation only to allow minimum of better planning
