### ISSUE TITLE
The game doesn't load

### ISSUE THREAD

**Issue by Skyhigh173** [awWhy/Fundamental#6]
I am new to this game and I haven't start yet, but I cant load into the game. I am playing on mobile so I can't show console :(

**Comment by awWhy** [comment]
Without any details, I can't find the issue. At best I can ask which browser version (I assume Safari) you are using

**Comment by awWhy** [comment]
Small update, it seems that mobile browsers do not load JS when being opened from memory (something like that), reload fixes it
