### ISSUE TITLE
add hotkeys to toggle autobuyers

### ISSUE THREAD

**Issue by miezebieze** [awWhy/Fundamental#7]
even with a touchscreen i find it mildly annoying to toggle the autobuyers off, whenever i want to save currency for something else and toggle all of them on again, one by one.

i'm about to get "Fe" and haven't found a reason to have only some of them active. so for now i think one key to switch the state of all of them at once would be fine. (alternatively two hotkeys to toggle all on/off.)

maybe add a button for this action as well.

**Comment by awWhy** [comment]
![image](https://user-images.githubusercontent.com/107661324/230301216-36327b19-e14d-416c-a94e-f78de645da48.png)

**Comment by miezebieze** [comment]
that doesn't do anything?

**Comment by awWhy** [comment]
There is already a hotkey for switching all auto toggle for a specific Stage
But you have to increase max level of 'New toggles' to 2
