### ISSUE TITLE
OMG..!!! All the Generator Autobuyer stop functioning..!!!

### ISSUE THREAD

**Issue by Liwers-Loor** [awWhy/Fundamental#8]
I've left my computer stay turned on to play Fundamental, and today I noticed it updates to v0.1.4, so I refresh the page..

I've already bought up to lv3 Generator Autobuyer for stage 4, and when I finished stage 3 and went into stage 4, it crashes me that the 3 Generator Autobuyers are still needs to buy, again..!

This must be a bug, since I ran several rounds of all 4 stages in v0.1.3 and the Generator Autobuyers were functioning correctly..

This bug might not just influence stage 4, but all other 3 stages, so please have a look into the codes.. It's nightmare to go through the stages without Generator Autobuyer from scratch a second time..!

Meow..!

**Comment by Liwers-Loor** [comment]
> 

Oops, I just check out, back to stage 1 and the problem appears again: all the Generator Autobuyer in stage 1 reset to null..

I just can't believe it..!

Meow..!

**Comment by Liwers-Loor** [comment]
> 

OK, further information ahead: before I reach stage 2 again, I purchased its lv4 Generator Autobuyer, then I finished stage 1 to go into the next stage.. Bravo..! The Generator Autobuyer comes back..!

So it means there is a malfunction occured to block the Generator Autobuyer from set itself on between different version of the game..

Here I recommend 2 solutions:
1. Look into the code to fix the problem..
2. Simply refund all the Generator Autobuyer's Strange Matter and ask us to rebuy them in the next patch..

Meow..!

**Comment by awWhy** [comment]
There is no malfunction, on discord was posted that auto research level will be set to 0 (because code that resets Stages have been reworked), while ignoring permanent level. That only affected all of the non Active Stages, and it will fix itself when you will return to same Stage you opened your game on
