### ISSUE TITLE
Game won't load

### ISSUE THREAD

**Issue by blisf** [awWhy/Fundamental#9]
Game won't load.

Using Firefox mobile. Was loading until today (playing for a month). 

Does work on chrome mobile. 

Link to browser info. 
https://whatismybrowser.com/w/GEAETQE

![Screenshot_20230725-103700_Firefox](https://github.com/awWhy/Fundamental/assets/35866788/a22f9e43-7249-42bb-8e42-5e4fee08277e)

**Comment by awWhy** [comment]
Mobile browsers require page reload once in a while (I don't know why)

**Comment by awWhy** [comment]
There also was some issue with Firefox and Screen reader support (fix been pushed)
Also all of that data is not required; All data I need is browser and any errors in console (not possible on phone, but next version should make errors appear outside of console)

**Comment by bathrobehero** [comment]
PC, Windows 11, Chrome, same issue.

**Comment by awWhy** [comment]
Any errors in console (I can't fix stuff without any information)

**Comment by bathrobehero** [comment]
Console:
```
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
Navigated to https://awwhy.github.io/Fundamental/
Code.js:50 Uncaught TypeError: Object.hasOwn is not a function
    at Ve (Code.js:50)
    at xt (Code.js:154)
    at Code.js:157
    at Code.js:165
```

And console after reload:
```
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
Navigated to https://awwhy.github.io/Fundamental/
Player.ts:1302 Uncaught TypeError: Object.hasOwn is not a function
    at Ve (Player.ts:1302)
    at xt (Main.ts:32)
    at Main.ts:72
    at Main.ts:485
```

**Comment by awWhy** [comment]
That error makes no sense, unless you didn't updated Chrome since 2021
That is Chrome bug (not this game), I can't fix it without downgrading game (replacing all Object.hasOwn with Object.prototype.hasOwnProperty.call)
Another thing that could had happen is one of chrome extension causing this issue

I would recommend using another browser until Chrome will fix it (I really dont want to deal with this error)
Or try to find what removes that function from browser

**Comment by awWhy** [comment]
Anyway that's chrome bug, I can't fix it without downgrading game (doing silly stuff like Object.prototype.hasOwnProperty.call)
So I would recommend using something else until they fix it
